name: Test script-worfkow.yml

on:
  push:
    branches: 
      - main

jobs:
  call-script:
    uses: mthurston/continuous-intelivery/.github/workflows/script-workflow.yml@main
    with:
      script: echo 'hello world!'
    #secrets: inherit